FROM mysql:latest

ARG MYSQL_ROOT_PASSWORD
ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

ARG MYSQL_DATABASE
ENV MYSQL_DATABASE=${MYSQL_DATABASE}

ARG MYSQLUSER
ENV MYSQLUSER=${MYSQLUSER}

ARG MYSQLHOST
ENV MYSQLHOST=${MYSQLHOST}

ARG MYSQLPORT
ENV MYSQLPORT=${MYSQLPORT}

ARG USERNAME
ENV USERNAME=${USERNAME}

ARG PASSWORD
ENV PASSWORD=${PASSWORD}


EXPOSE 3306
